### ISSUE TITLE
Repo name does not follow Homebrew rules

### ISSUE THREAD

**Issue by Gummibeer** [owenvoke/homebrew-casks#1]
The correct naming would be `owenvoke/homebrew-casks` to install it as `owenvoke/casks`.

https://docs.brew.sh/Taps
> On GitHub, your repository must be named homebrew-something in order to use the one-argument form of brew tap. The prefix ‘homebrew-‘ is not optional. (The two-argument form doesn’t have this limitation, but it forces you to give the full URL explicitly.)

**Comment by owenvoke** [comment]
Thanks @Gummibeer, I've now renamed it and will update any references in the README. 👍
